# Test script to verify Flask app setup
import os

print("Checking required files...")

required_files = [
    'app.py',
    'templates/index.html',
    'templates/result.html',
    'requirements.txt',
    'gender_label_encoder.pkl',
    'diabetic_label_encoder.pkl',
    'smoker_label_encoder.pkl',
    'region_label_encoder.pkl',
    'scaler.pkl',
    'best_model.pkl'
]

missing_files = []
for file in required_files:
    if os.path.exists(file):
        print(f"✓ {file}")
    else:
        print(f"✗ {file} - MISSING")
        missing_files.append(file)

print("\n" + "="*50)
if missing_files:
    print("⚠️  Missing files detected!")
    print("\nModel files (*.pkl) need to be generated by running the notebook.")
    print("Please run all cells in 'analysis_model.ipynb' first.")
else:
    print("✅ All required files are present!")
    print("\nYou can now run the Flask app:")
    print("  python app.py")
